package com.pgm.gui;

import com.pgm.biz.Editor;
import com.pgm.biz.pojo.Imagen;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ExecGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();
        jButtonRotIzq = new javax.swing.JButton();
        jButtonRotDer = new javax.swing.JButton();
        jButtonFlipHor = new javax.swing.JButton();
        jButtonFlipVer = new javax.swing.JButton();
        jButtonNegativo = new javax.swing.JButton();
        jButtonDesenfocar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabelImagen.setText(" ");
        jLabelImagen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelImagenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabelImagen.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabelImagenMouseWheelMoved(evt);
            }
        });

        jButtonRotIzq.setText("Girar izquierda");
        jButtonRotIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotIzqActionPerformed(evt);
            }
        });

        jButtonRotDer.setText("Girar derecha");
        jButtonRotDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotDerActionPerformed(evt);
            }
        });

        jButtonFlipHor.setText("Flip horizontal.");
        jButtonFlipHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipHorActionPerformed(evt);
            }
        });

        jButtonFlipVer.setText("Flip vertical.");
        jButtonFlipVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipVerActionPerformed(evt);
            }
        });

        jButtonNegativo.setText("Negativo");
        jButtonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativoActionPerformed(evt);
            }
        });

        jButtonDesenfocar.setText("Desenfocar");
        jButtonDesenfocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesenfocarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRotDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFlipHor, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonFlipVer, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonDesenfocar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonRotIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRotIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRotDer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFlipHor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFlipVer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDesenfocar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelImagenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelImagenAncestorAdded
        // TODO add your handling code here:
/*
        // Create a 4x4 BufferedImage
        int[][] datos = getPGM();
        int width = datos.length;
        int height = datos.length;
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

        // Set all pixels to red
        int white = 0 << 16 | 0 << 8 | 0;// RGB value for red
        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                white = datos[y][x] << 16 | datos[y][x] << 8 | datos[y][x];
                image.setRGB(x, y, white);
            }
        }

        // Save the image as a JPG file
        File outputFile = new File("red_image.jpg");
        try {
            ImageIO.write(image, "jpg", outputFile);
            System.out.println("Image saved successfully.");
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        }

        ImageIcon i = new ImageIcon(image);
        System.out.println(i.getImage());
        this.jLabel1.setIcon(i);

         */
    }//GEN-LAST:event_jLabelImagenAncestorAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        try {
            editor = new Editor("perro.pgm");
            preview();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }

    }//GEN-LAST:event_formWindowActivated

    private void jLabelImagenMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabelImagenMouseWheelMoved
        // TODO add your handling code here:
        System.out.println("aaaaaa");
    }//GEN-LAST:event_jLabelImagenMouseWheelMoved

    private void jButtonRotIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotIzqActionPerformed
        // TODO add your handling code here:

        editor.rotIzquierda();

        preview();

    }//GEN-LAST:event_jButtonRotIzqActionPerformed

    private void jButtonRotDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotDerActionPerformed
        // TODO add your handling code here:
        editor.rotDerecha();

        preview();
    }//GEN-LAST:event_jButtonRotDerActionPerformed

    private void jButtonFlipHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipHorActionPerformed
        // TODO add your handling code here:
        editor.flipHorizontal();
        preview();
    }//GEN-LAST:event_jButtonFlipHorActionPerformed

    private void jButtonFlipVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipVerActionPerformed
        // TODO add your handling code here:
        editor.flipVertital();
        preview();
    }//GEN-LAST:event_jButtonFlipVerActionPerformed

    private void jButtonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativoActionPerformed
        // TODO add your handling code here:
        editor.negativo();
        preview();
    }//GEN-LAST:event_jButtonNegativoActionPerformed

    private void jButtonDesenfocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesenfocarActionPerformed
        // TODO add your handling code here:
        editor.desenfocar();
        preview();
    }//GEN-LAST:event_jButtonDesenfocarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void preview() {
        int[][] datos = editor.toInt();
        int nFilas = datos.length;
        int nColumnas = datos[0].length;
        int rgb;

        BufferedImage image = new BufferedImage(nColumnas, nFilas, BufferedImage.TYPE_INT_RGB);

        // Set all pixels to red
        for (int f = 0; f < nFilas; f++) {
            for (int c = 0; c < nColumnas; c++) {
                rgb = datos[f][c] << 16 | datos[f][c] << 8 | datos[f][c];
                image.setRGB(c, f, rgb);
            }
        }

        //Image newImage = image.getScaledInstance(745, 745, Image.SCALE_DEFAULT);
        ImageIcon i = new ImageIcon(image);

        calcTamañoVentana(nColumnas, nFilas);
        this.jLabelImagen.setIcon(i);

    }

    private void calcTamañoVentana(int ancho, int altura) {

        if (altura < 525) {
            this.setSize(ancho + 165, 525);

        } else {
            this.setSize(ancho + 165, altura + 50);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }

    private Editor editor = null;
    private Imagen imagen = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesenfocar;
    private javax.swing.JButton jButtonFlipHor;
    private javax.swing.JButton jButtonFlipVer;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNegativo;
    private javax.swing.JButton jButtonRotDer;
    private javax.swing.JButton jButtonRotIzq;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
