package com.pgm.gui;

import com.editor.pgm.exceptions.FileWriteError;
import com.pgm.biz.Editor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ExecGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();
        jButtonRotIzq = new javax.swing.JButton();
        jButtonRotDer = new javax.swing.JButton();
        jButtonFlipHor = new javax.swing.JButton();
        jButtonFlipVer = new javax.swing.JButton();
        jButtonNegativo = new javax.swing.JButton();
        jButtonDesenfocar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelImagen.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setText("Cargando...");

        jButtonRotIzq.setText("Girar izquierda");
        jButtonRotIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotIzqActionPerformed(evt);
            }
        });

        jButtonRotDer.setText("Girar derecha");
        jButtonRotDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotDerActionPerformed(evt);
            }
        });

        jButtonFlipHor.setText("Flip horizontal.");
        jButtonFlipHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipHorActionPerformed(evt);
            }
        });

        jButtonFlipVer.setText("Flip vertical.");
        jButtonFlipVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipVerActionPerformed(evt);
            }
        });

        jButtonNegativo.setText("Negativo");
        jButtonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativoActionPerformed(evt);
            }
        });

        jButtonDesenfocar.setText("Desenfocar");
        jButtonDesenfocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesenfocarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRotDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFlipHor, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonFlipVer, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonDesenfocar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonRotIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRotIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRotDer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFlipHor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFlipVer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDesenfocar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRotIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotIzqActionPerformed
        // TODO add your handling code here:
        editor.rotIzquierda();
        preview();
    }//GEN-LAST:event_jButtonRotIzqActionPerformed

    private void jButtonRotDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotDerActionPerformed
        // TODO add your handling code here:
        editor.rotDerecha();
        preview();
    }//GEN-LAST:event_jButtonRotDerActionPerformed

    private void jButtonFlipHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipHorActionPerformed
        // TODO add your handling code here:
        editor.flipHorizontal();
        preview();
    }//GEN-LAST:event_jButtonFlipHorActionPerformed

    private void jButtonFlipVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipVerActionPerformed
        // TODO add your handling code here:
        editor.flipVertital();
        preview();
    }//GEN-LAST:event_jButtonFlipVerActionPerformed

    private void jButtonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativoActionPerformed
        // TODO add your handling code here:
        editor.negativo();
        preview();
    }//GEN-LAST:event_jButtonNegativoActionPerformed

    private void jButtonDesenfocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesenfocarActionPerformed
        // TODO add your handling code here:
        editor.desenfocar();
        preview();
    }//GEN-LAST:event_jButtonDesenfocarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        GuardarJDialog gd = new GuardarJDialog(this, true);
        gd.setVisible(true);

        JRootPane rp = (JRootPane) gd.getComponent(0);
        JLayeredPane lp = (JLayeredPane) rp.getComponent(1);
        JPanel p = (JPanel) lp.getComponent(0);
        JTextField tf = (JTextField) p.getComponent(1);

        String nombre = tf.getText();

        if (!nombre.endsWith(".pgm")) {
            nombre += ".pgm";
        }

        try {
            editor.toWrite(nombre);
        } catch (FileWriteError e) {
            ed.setErrorText(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Centra el UI en la pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        RutaJDialog rd = new RutaJDialog(this, true);

        do {
            rd.setVisible(true);

            JRootPane rp = (JRootPane) rd.getComponent(0);
            JLayeredPane lp = (JLayeredPane) rp.getComponent(1);
            JPanel p = (JPanel) lp.getComponent(0);
            JTextField tf = (JTextField) p.getComponent(1);

            String ruta = tf.getText();

            try {
                editor = new Editor(ruta);
                this.jLabelImagen.setText("");
                preview();
                ed.dispose();
            } catch (Exception e) {
                ed.setErrorText(e);
                ed.setVisible(true);
            }

        } while (editor == null);
    }//GEN-LAST:event_formWindowOpened

    private void preview() {
        int[][] datos = editor.toInt();
        int nFilas = datos.length;
        int nColumnas = datos[0].length;
        int rgb;

        BufferedImage image = new BufferedImage(nColumnas, nFilas, BufferedImage.TYPE_INT_RGB);

        // Transformamos la escala de grises a rgb
        for (int f = 0; f < nFilas; f++) {
            for (int c = 0; c < nColumnas; c++) {
                rgb = datos[f][c] << 16 | datos[f][c] << 8 | datos[f][c];
                image.setRGB(c, f, rgb);
            }
        }

        //Image newImage = image.getScaledInstance(745, 745, Image.SCALE_DEFAULT);
        ImageIcon i = new ImageIcon(image);

        calcTamañoVentana(nColumnas, nFilas);
        this.jLabelImagen.setIcon(i);

    }

    private void calcTamañoVentana(int ancho, int altura) {

        if (altura < 525) {
            this.setSize(ancho + 165, 670);

        } else {
            this.setSize(ancho + 165, altura + 50);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }

    private Editor editor = null;
    ErrorJDialog ed = new ErrorJDialog(this, true);


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesenfocar;
    private javax.swing.JButton jButtonFlipHor;
    private javax.swing.JButton jButtonFlipVer;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNegativo;
    private javax.swing.JButton jButtonRotDer;
    private javax.swing.JButton jButtonRotIzq;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
